sudo: required

services:
  - docker

before_install:
  - docker build -t sayemsarkar123/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sayemsarkar123/client-test npm run test

after_success:
  - docker build -t sayemsarkar123/multi-client ./client
  - docker build -t sayemsarkar123/multi-server ./server
  - docker build -t sayemsarkar123/multi-worker ./worker
  - docker build -t sayemsarkar123/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sayemsarkar123/multi-client
  - docker push sayemsarkar123/multi-server
  - docker push sayemsarkar123/multi-worker
  - docker push sayemsarkar123/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-928476053608'
  bucket_path: 'multi-docker'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
