version: '3'
services:
  client:
    image: 'sayemsarkar123/multi-client'
  backend:
    image: 'sayemsarkar123/multi-backend'
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'sayemsarkar123/multi-worker'
  nginx:
    image: 'sayemsarkar123/multi-nginx'
    ports:
      - '80:80'
