version: '3'
services:
  client:
    image: 'sayemsarkar123/multi-client'
    hostname: frontend
  backend:
    image: 'sayemsarkar123/multi-server'
    hostname: backend
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'sayemsarkar123/multi-worker'
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'sayemsarkar123/multi-nginx'
    hostname: nginx
    ports:
      - '80:80'
